### ISSUE TITLE
Cemu 1.11.1 doesn't run on Vega

### ISSUE THREAD

**Issue by oscarbg** [mikakev1/mesa_mild_compatibility#1]
Hi,
build mesa_mild with LLVM 5.0 as needed for AMDGPU Vega driver and running Cemu 1.11.1 with all options needed I get eventually:

```
LLVM ERROR: Cannot select: 0x7f71a053e0e8: f16 = bitcast 0x7f71a054fb58
  0x7f71a054fb58: i32 = srl 0x7f71a054faf0, Constant:i32<16>
    0x7f71a054faf0: i32 = bswap 0x7f71a054abd8
      0x7f71a054abd8: i32 = and 0x7f71a053dcd8, Constant:i32<65535>
        0x7f71a053dcd8: i32 = extract_vector_elt 0x7f71a053dc70, Constant:i32<0>
          0x7f71a053dc70: v4i32 = bitcast 0x7f71a053b568
            0x7f71a053b568: v4f32,ch = BUFFER_LOAD_FORMAT<LD16[TargetCustom7]> 0x7f71a04d63c8, 0x7f71a053b6a0, 0x7f71a05391b8, Constant:i32<0>, Constant:i1<0>, Constant:i1<0>
              0x7f71a053b6a0: v4i32,ch = load<LD16[%23(addrspace=2)](dereferenceable)(invariant)> 0x7f71a04d63c8, 0x7f71a053b638, undef:i64
                0x7f71a053b638: i64 = add 0x7f71a05388c8, Constant:i64<32>
                  0x7f71a05388c8: i64,ch = CopyFromReg 0x7f71a04d63c8, Register:i64 %vreg4
                  0x7f71a053b5d0: i64 = Constant<32>
                0x7f71a0539358: i64 = undef
              0x7f71a05391b8: i32,ch = CopyFromReg 0x7f71a04d63c8, Register:i32 %vreg15
                0x7f71a0539150: i32 = Register %vreg15
              0x7f71a0539490: i32 = Constant<0>
              0x7f71a053b360: i1 = Constant<0>
              0x7f71a053b360: i1 = Constant<0>
          0x7f71a0539490: i32 = Constant<0>
        0x7f71a0538658: i32 = Constant<65535>
    0x7f71a053fb00: i32 = Constant<16>
In function: main
```
so seems a LLVM error right? should upgrade to LLVM 6.0?

**Comment by mikakev1** [comment]
I could never test on vega. I cannot tell.

**Comment by oscarbg** [comment]
no problem..
sad also tested with LLVM6.0git with same error..
guess then it's a Mesa bug and will keep testing your updated Mesa branch for fixes and probably ping to Mesa-devs..

**Comment by mikakev1** [comment]
I do not think it's a mesa (upstream) bug.
I guess Cemu uses some more extentions when creating a context and this function is not working in compat. So maybe disabling it would work, but unfortunately, I cannot test and see if I can find a workaround.

**Comment by Kierek** [comment]
I experience the same problem with my RX 580. Is this also not supposed to work on Polaris? It works fine(even though very slow) on Intel HD 530.

I've used mesa mild aur package with clang and llvm from lcarlier's mesa-git repo.

**Comment by mikakev1** [comment]
Ah, if you want to debug, it's not sufficient :
You have to dump wine's opengl request, maybe you want to do that :
	export WINEDEBUG="+opengl,+wgl"
	export MESA_DEBUG=context
	export MESA_GLSL=log
	export MESA_GLSL_CACHE_DISABLE=true
        export GALLIUM_HUD=fps,cpu,VRAM-usage,num-compilations,GPU-load

**Comment by Kierek** [comment]
I'm not really sure what I should be looking at, so here are my logs. What I found is that after removing all shader cache(renamed shaderCache folder) I can see an image, but it almost immediately crashes.

Checked on Mario Kart 8 and cemu 1.8.2b. I would love to test it on the newest one, but it crashes all the time. On this one I'm at least able to "play" Mario Kart, altough in 40fps, since it only works with Intel HD (for the time being i hope!)

[log.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1553246/log.txt)
[log no shader cache.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1553248/log.no.shader.cache.txt)

**Comment by Zacharybinx34** [comment]
Really wish this worked with Vega!

**Comment by oscarbg** [comment]
yes as AMDGPU Pro works but it's a very slow OPenGL driver..

2017-12-27 20:48 GMT+01:00 Zacharybinx34 <notifications@github.com>:

**Comment by mikakev1** [comment]
@Kierek  : You experience a problem with shader compilation.
And by dumping shaders MESA_GLSL=log,dump, you'll endup with GLSL sources with compilation status appended in the file (grep is your friend). Then you could find which one failed (it should be in cemu's log too)

Now, there is another backend called NIR, that's not fully functional but it follows a different codepath, it  should be sufficient nonetheless.
Maybe now it's worth trying it?

**Comment by mikakev1** [comment]
#2
