### ISSUE TITLE
Was trying this for a few days, what I noticed

### ISSUE THREAD

**Issue by epigramx** [mikakev1/mesa_mild_compatibility#1]
Specs: R9 290 GPU + also iGPU of Haswell (on i7-4790K).

I suspect your R9 270x causes different behavior.

Intel on the Haswell iGPU seemed to be able to correctly render WWHD but it was relatively slow. It crashed on load of BotW.

Radeonsi for the R9 290 GPU appears to not show fonts on the UI of WWHD and it also crashed on load of BotW.

This area in general seems quite incomplete for fast usage. I was hoping for a quick automatic method to give to other users. It appears it needs a lot of configuration that is tailor made for a specific GPU model.

PS. What model is your Intel iGPU?

**Comment by epigramx** [comment]
In addition, I tried different kernels and behavior was similar/same, different LLVM versions (from 3.9.1 to 5) and behavior was similar/same. and I also patched different mesa versions from the patch you posted on the mailist list and the behavior was again similar/same.

**Comment by mikakev1** [comment]
Ok, sorry for the late answer, I was caught elsewhere.
I just pushed an update today, I'm testing it.

- I use IGD from I5 4440, but I need to override vendors to be able to render (more) correctly.
    Anyway you should not expect too much unless you own an Iris GPU which is likely to have the required horse power.
- I couldn't say anything about WWHD, I only own BOTW and XCX.


- Be careful if you use -O2 -march native when building with an haswell, a recent commit broke steam 
- Same with wine, I have garbled text unless I get it from package maintainer. "-O2" seems to be too much with haswell right now, it was working fine with both earlier this month.


As you may understand, I cannot test every setup, and as I use only RADEON kernel drivers, what happens to AMDGPU, has to be tested by someone else.

**Comment by mikakev1** [comment]
In any case, could you provide me once (and if) you rebuild from this repository a screen shot, and if it's not too much send me the last 100 lines output by 

MESA_DEBUG=context WINEDEBUG="+opengl"  MESA_VENDOR_OVERRIDE="mesa" MESA_RENDERER="mesa" MESA_GL_VERSION_OVERRIDE=4.5COMPAT wine Cemu.exe 

---

Be careful, now you need to edit the binary as described in this repository's "README.md" to replace the single occurence of "#version 420" by "#version 450" 

Which version of Cemu are you trying. (the tips above applies to 1.8.0 and 1.8.1)?

For previous ( 1.7.4 and below) an unmodified mesa worked provided you used driconf's "allow ... enhanced compatibility for application that ..." and MESA_GL_VERSION_OVERRIDE=4.5COMPAT

**Comment by mikakev1** [comment]
Closing, was applicable on previous version.
