### ISSUE TITLE
Cemu Error from Wine with newest version

### ISSUE THREAD

**Issue by Zacharybinx34** [mikakev1/mesa_mild_compatibility#13]
I have it installed on antergos, but getting an error when loading cemu

wxWidgets Debug Alert
.....\src\msw\window.cpp(3645): assert ""wclass" failed in wxWindow::MSWCreate(): failed to register window class?
Do you want to stop the program?

Vega 64 - Kernel 4.16.1 - llvm7 - etc.

**Comment by TheYoshiGuy** [comment]
Hi Zachary,

I've got this issue too, you can actually just press 'cancel' in the dialogue box and cemu will keep working. The issue appears to be cemu-hook not working drawing the UI properly in wine, I don't think it's a mesa_mild issue.

Ryzen5 1600X - Vega56 - Kernel 4.15.12 - llvm7

**Comment by Zacharybinx34** [comment]
I get the following terminal error:

        0x7f235c48f6b0: i32 = extract_vector_elt 0x7f235c48ea00, Constant:i32<0>
          0x7f235c48ea00: v2i32 = bitcast 0x7f235c48bc78
            0x7f235c48bc78: v2f32,ch = BUFFER_LOAD_FORMAT<LD8[TargetCustom7(addrspace=2)](align=1)(dereferenceable)> 0x7f235c119310, 0x7f235c48bdb0, 0x7f235c486eb8, Constant:i32<0>, Constant:i1<0>, Constant:i1<0>
              0x7f235c48bdb0: v4i32,ch = load<LD16[%23(addrspace=2)](dereferenceable)(invariant)> 0x7f235c119310, 0x7f235c48bd48, undef:i64
                0x7f235c48bd48: i64 = add 0x7f235c486908, Constant:i64<32>
                  0x7f235c486908: i64,ch = CopyFromReg 0x7f235c119310, Register:i64 %8

                  0x7f235c48bce0: i64 = Constant<32>
                0x7f235c487058: i64 = undef
              0x7f235c486eb8: i32,ch = CopyFromReg 0x7f235c119310, Register:i32 %15
                0x7f235c486e50: i32 = Register %15
              0x7f235c487190: i32 = Constant<0>
              0x7f235c48ba70: i1 = Constant<0>
              0x7f235c48ba70: i1 = Constant<0>
          0x7f235c487190: i32 = Constant<0>
        0x7f235c48fe68: i32 = Constant<65535>
    0x7f235c492ee0: i32 = Constant<16>
In function: main

**Comment by TheYoshiGuy** [comment]
Yeah that's what I'm saying , close this issue and don't waste the dev's time lol.
