### ISSUE TITLE
Please add much needed support for Vega through kernel 4.17

### ISSUE THREAD

**Issue by Zacharybinx34** [mikakev1/mesa_mild_compatibility#16]
Would be much appreciated!

Thank you!

**Comment by Xalphenos** [comment]
Pretty sure that's an upstream issue.  So there really isn't any point in you doing this every kernel update.  Also there have been two users report moderate success with vega + mesa mild + cemu.

**Comment by Zacharybinx34** [comment]
What do you mean it's an upstream issue?

This new kernel has added much Vega support.

**Comment by TheYoshiGuy** [comment]
Yep, I've had success with:
Kernel: 4.15 (still, due to laziness)
Distro: Arch
GPU: Vega56
LLVM: 7
Driver: mesa_mild

I can run BOTW without the black texture issue which I had with my RX580.

**Comment by mikakev1** [comment]
I can't go further  than upstream on any component (llvm, kernel, mesa, libdrm).
