### ISSUE TITLE
[VEGA] Hard lock when opening Mario Kart 8

### ISSUE THREAD

**Issue by TheYoshiGuy** [mikakev1/mesa_mild_compatibility#18]
When opening Mario Kart 8 on Antergos, the system completely locks and I have to REISUB to bring the system back online. The following is spammed in my dmesg log: 

https://pastebin.com/8PkhUF1J

Here is a sniped:

`Jun 07 15:56:07 nihonium2 kernel: amdgpu 0000:0c:00.0: [gfxhub] VMC page fault (src_id:0 ring:155 vmid:6 pas_id:0)
Jun 07 15:56:07 nihonium2 kernel: amdgpu 0000:0c:00.0:   at page 0x00008001415dc000 from 27
Jun 07 15:56:07 nihonium2 kernel: amdgpu 0000:0c:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Jun 07 15:56:17 nihonium2 kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, last signaled seq=335182, last emitted seq=335185`

I have been able to reproduce this on the following systems, with various versions of cemu, the kernel, mesa_mild, wine as well as various settings with Cemu (I've accumulated at least 5 hours of time trying to get this to work):

-- System 1 --
Ryzen 1600X
16GB RAM
RX Vega 56

-- System 2 --
Ryzen 2700X
16GB RAM
RX Vega 64

uname -a
Linux nihonium2 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux

I dumped my game more than once, and can confirm that the dump is good because it works on my wife's computer with a Nvidia GPU. It also worked on System 1 before I upgraded the RX470 to a Vega56.

I'm happy to test anything for you, submit logs, and even provide AnyDesk access to one of the systems if that helps get this working.

Also note that I've seen other users on github, reddit and discord with mesa_mild and RX Vega cards complain about this exact same problem in Mario Kart 8.

**Comment by mikakev1** [comment]
Argh I just bought and RX480, and I do not own a VEGA56.
Let's wait until 4.17 goes to distribution with its lots of fixes.
By the way did you try using "core" profile or "compatibility" profile, or both?

**Comment by TheYoshiGuy** [comment]
Yeah, I tried using the "core" profile, which leaves me hanging on a black screen but doesn't hard-lock the system, and I tried the compatibility profile, which locks the system.

I didn't try them both at the same time though like the guy in the other thread was doing :)

Yeah, I'm looking forward to Kernel 4.17 moving out of testing.
I won't get my hopes up though because during my research I found this: https://bugs.freedesktop.org/show_bug.cgi?id=105251

Comment 7 in that thread mentions mesa_mild + cemu, and comment 4 mentions "Got the issue on kernel 4.17-rc6 with Mesa 18.2 built against LLVM 7.0."

P.S. Congrats on your new Polaris card purchase, and thanks for sharing this hobby project here, it's been great being able to play my Wii U games in higher resolution on the PC.

**Comment by TheYoshiGuy** [comment]
So with:

Kernel: 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
Driver: OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.2.0-mild (git-9c85f57dbc)

The problem persists, hard lock when opening Mario Kart 8 in cemu.

**Comment by TheYoshiGuy** [comment]
@mikakev1 So now that cemu works in mainline mesa 18.2, I've tested and unfortunately this issue is still present there.
Not your problem.
