### ISSUE TITLE
Cemu works in Mesa 18.2 mainline now

### ISSUE THREAD

**Issue by TheYoshiGuy** [mikakev1/mesa_mild_compatibility#19]
Hey Mikakev1, 
Just letting you know that a couple of us have verified that Cemu now works in mesa 18.2.
If you're only doing this project for Cemu, you probably don't have to any more.
I tested this with a Vega card, Xalphenos from discord has tested it with a polaris and fiji card.

**Comment by mikakev1** [comment]
Hi that was expected since compatibility profile has been largely improve thanks to the upstream work.
That's one thing less to care for in my life. :)
Let's close these things down so there's no confusion.
