### ISSUE TITLE
No Man Sky support

### ISSUE THREAD

**Issue by oscarbg** [mikakev1/mesa_mild_compatibility#3]
Hi,
seems a great product!

original No Man Sky release required OpenGL 4.5 compat mode with intel igpus didn't have..
then in March a update came with Intel GPU supports so requeriments we lowered to OpenGL 4.4 seems..
altough now Intel GPUs support OpenGL 4.5 on windows game don't need it seem..
sad Mesa still has no compat support so asking if this library is expected to be able to run it via Wine..

note: No Mans Sky works in Wine with NV GPUs..

thanks:

**Comment by mikakev1** [comment]
Hi,
I cannot tell, best thing I could say, is that it's not harmful to give it a try.

However I'll assume you've already tried with this setup  (check driconf)

- Enable 'Force GLSL extension default behavior to warn'
- Enable 'Allow a higher compat profile (version 3.1+) for apps that request it.

And that you started the application with 
`MESA_GL_VERSION_OVERRIDE=4.5COMPAT wine <application.exe>`
If you haven't, you should give it a try.

Now, if it's not better, you may proceed to the following steps.

1° Build mesa using this repository, like you would do as usual, pay attention to libdrm's version.

Now you have two pathes, let's try with the first.
(A)
2-A) Setup with driconf your driver's options : 
- Disable 'Enable offlading GL driver work to a separate thread'
- Enable 'Allow a relaxed core profile'
- Enable 'Force GLSL extension default behavior to warn'
3-A) Start your application, including this environment variable set MESA_GL_VERSION_OVERRIDE=4.5
it's better if you do it all in one command, like this, so you won't pollute your env :
`MESA_GL_VERSION_OVERRIDE=4.5 wine <application.exe>`
Maybe you will need to change directory beforehand (to where the application is located).

Try and let me now if it's better
------------------------------------------
if (A) doesn't work, try this:
2-B In driconf set these options.

- Disable 'Allow a relaxed core profile'
- Enable 'Force GLSL extension default behavior to warn'
- Enable 'Allow a higher compat profile (version 3.1+) for apps that request it.

3-B Launch your application with 
`MESA_GL_VERSION_OVERRIDE=4.5COMPAT wine <application.exe>`

Again tell me if it's better.

**Comment by mikakev1** [comment]
The issue will be close in few days because there is no update.

**Comment by oscarbg** [comment]
just had tested old version.. so seems new version doesn't require compat profile.. in fact using MESA_GL_VERSION_OVERRIDE=4.5COMPAT we get a black screen in game..
instead without it at least renders but with graphical corruption.. 
even using padoka ppa mesa the game randers with same issues as you repo..
so seems graphics bugs in mesa drivers at least i965 don't know radeonsi..
thanks..
