### ISSUE TITLE
any help with this glitch please

### ISSUE THREAD

**Issue by sil3ntkilr** [mikakev1/mesa_mild_compatibility#3]
When I start Zelda BOTW, I get this;
https://imgur.com/Tkqtf68
https://imgur.com/a/nyMsS

**Comment by mikakev1** [comment]
It seems that DSA is unoperative.
Have you edited the executable?
Have you started cemu forcing compatibility profile?

**Comment by sil3ntkilr** [comment]
Sorry i am noob to linux. Can you eloborate on that please

**Comment by mikakev1** [comment]
Check the frontpage of this github repository.
