### ISSUE TITLE
i need instruction for install in ubuntu

### ISSUE THREAD

**Issue by gospel1988** [mikakev1/mesa_mild_compatibility#4]
hi bro 
can you make the steps for install in ubuntu please

**Comment by mikakev1** [comment]
Hi bro.
As there is a lot of different distribution, and I use arch and gentoo, I lack the "bandwith" to test everything.

It a normal "build mesa from git on ubuntu" process, check if you find documentation.

Maybe this one will be fine for you?

https://www.gamingonlinux.com/wiki/Building_Mesa_from_source

Just change the line :

`git clone git://anongit.freedesktop.org/mesa/mesa`

With 

`git clone https://github/mikakev1/mesa_mild_compatibility`

**Comment by gospel1988** [comment]
thx for aswer
yesterday i try to install whit manjaro and all works 
but to the last step when  run "sudo pacman -Syy mesagit" dont install all the pkg anly 4 or 6 
and when i go into /pkgbuild/ and right click to open term then type ./buildmesa.sh the same only 3 or 4 
and i can open cemu and look so bad only lines 
please can you help me

**Comment by mikakev1** [comment]
Can you give me your specs, and the application/game you're trying to run over Cemu?
I guess that if in the last step, you run ' "sudo pacman -Syy mesagit", you're going to remove what you just built.
- When it has been built once, **succesfully**, things get easier, just run "./buildmesa.sh"

By the way here's a checklist :

Checklist :

    "~/.drirc" must contain these key/values (you can use driconf):
    < option name="force_glsl_extensions_warn" value="true" / >
    < option name="allow_higher_compat_version" value="true" / >
    < option name="allow_relaxed_core_profile" value="false" / >
    < option name="mesa_no_error" value="false" / >
    Check your commandline, it must at least contain
    MESA_VERSION_OVERRIDE=4.5COMPAT wine64 Cemu.exe
    Remove shaderCache
    Check that [generic] appears on the titlebar. Cemu must not know on which kind of GPU it's running.
    Use either WINE's CSMT or this key/value, but not both
    < option name="mesa_glthread" value="true" / >
    Check you replaced "#version 420" by "#version 450" in the Cemu.exe file.

**Comment by gospel1988** [comment]
sure
fx 8350 stock 4.0gz
rx 480 8gb 
8gb ram 1866 two slots
i make all like say dev in his tutorial 
an only with the two finals steps make me error dont install mesagit and ./buildmesa.sh

**Comment by Gamedev1909** [comment]
I am going to work on another video here soon don’t worry we have new info I have to add for manajro

**Comment by gospel1988** [comment]
Okay, I am looking forward
thx i make all your steps and is good i like linux for real 
i only try whit botw and i dont see nothing and only say gpu Generic and have 15fps but i can install mesagit
because in windows its 10 or 15 fps and i dont see bad my aspec

**Comment by mikakev1** [comment]
Ok, this could be normal, maybe everything has been done correctly.
You're the second person with a Polaris, that tries, so far it was unsuccessful :
I did tried to help, the first one, but it's not the same thing as being behind the keyboard, with the same GPU and more than everything else on the same timezone.
Maybe something was wrong then, maybe it's better now, and you'll end up being successful.
In any cases  you can count on me, to help you, not only because I'm a nice guy, but also because I'm curious about Polaris. :)


I'm going to build "generic" packages, give you a link to download them, and guide you through their installation. So I'll be able to skip the setup phase, and ensure it has been done correctly.

Do you ONLY have a RX480? (I mean can I remove others GPU's support)


Are you ok with that?

**Comment by gospel1988** [comment]
yes i have a r7 370 4gb is worse i tink

**Comment by gospel1988** [comment]
yes im ok in all games play so good

But I obsessed with cemu

**Comment by mikakev1** [comment]
R7 370 would work, I have a modded 270X with an 370X bios.

**Comment by mikakev1** [comment]
could you send me the result of 
`cat /proc/cpuinfo | grep -i model | sort -u`

**Comment by gospel1988** [comment]
yes i play good whit that card in windows even use speed hack 
but is in my work JJJJ
the mine is the rx 480 is a powerfull card i dont now whats dont work good in cemu, RPCS3 works perfect for me in 17.7.1 in some games
another think under windows cemu 1.8.2b wors great zelda twilight princess 30 fps full stable no down any place and smash 4 is 50 and 60 fps i dont now how botw dont work property 
This is a subliminal message like buy a N . V . I . D . I .A OR I. N, T. E. L. JAJAJAJA
in spanish NVIDIA say envy jjjjjjjj

**Comment by mikakev1** [comment]
Are you mexican?

**Comment by gospel1988** [comment]
NOOOOO Guatemalteco

**Comment by gospel1988** [comment]
central america

**Comment by mikakev1** [comment]
Mis amigos de Mexico dicen "jajajajaja" tambien  :)

**Comment by mikakev1** [comment]
Podria usted darme el resultado que yo he pedido? Tengo que conocer a las specificaciones del Bulldozer

**Comment by gospel1988** [comment]
perdon esque estoy ahorita en trabajo pero seguro seguro te lo envio por la noche

**Comment by mikakev1** [comment]
Gracias. Yo puedo esperar sin problema.

**Comment by gospel1988** [comment]
tu hablas español???

**Comment by mikakev1** [comment]
No, yo tengo un gato que le hable :)

**Comment by gospel1988** [comment]
ok

**Comment by gospel1988** [comment]
then is the gpu incompatible with your mesa???
for that dont intall mesagit and the other???

**Comment by mikakev1** [comment]
Fuimos  en barcelona  martes. 
No, last time I did not try myself, so there is a possibility something went wrong, that's why I proposed to build them.

At the moment I can only say that it works on IGPU (haswell and skylake), and on amd's GCN 1.0, 1.1
I simply needs more users, to gather more results.

**Comment by gospel1988** [comment]
Ok I hope we can solve it. As amd with so much experience can have such a mediocre openGL
The rx 480 is not a low-end or much less cheap card 
estoy decepcionado

**Comment by gospel1988** [comment]
how its work whit the drivers amd pro (linux)???
dont you know??

**Comment by Gamedev1909** [comment]
ok now working on ubuntu build instructions

**Comment by gospel1988** [comment]
ok thx for that 
only can you make a video whit your zelda botw working in 30fps

**Comment by Gamedev1909** [comment]
if i do a video using cpu encoder fps will drop to 25

**Comment by gospel1988** [comment]
Ok I saw it in your video generic gpu and you img say amdgpu
is a diferent installation

**Comment by Gamedev1909** [comment]
no we can change the name on cemu to amdgpu-pro to fix render bugs thats all

**Comment by gospel1988** [comment]
you use amdgpu-pro to whit mesa???

**Comment by Gamedev1909** [comment]
no and right now i am having a bad time compiling this for ubuntu

**Comment by Gamedev1909** [comment]
configure: error: LLVM 3.9.0 or newer is required for r600

**Comment by gospel1988** [comment]
installing what??? gpu-pro??

**Comment by Gamedev1909** [comment]
@mikakev1 does scons build and install?

**Comment by gospel1988** [comment]
I hope you get to 100% to be able to install it once and for all the only problem I see is that we have different cpu and gpu

**Comment by gospel1988** [comment]
i read is some place you say use amdgpu-pro whitout a problems 
works good cemu works good in manjaro only whit de amd drivers???

**Comment by Gamedev1909** [comment]
Ok killed Ubuntu haha it’s much harder on Ubuntu it has many issues

**Comment by Gamedev1909** [comment]
ok so went through hell killed Ubuntu 3 times and after each install the DE wont load

**Comment by gospel1988** [comment]
ok dont worry
look i do this 
sudo pacman -S yaourt 
yaourt driconf 
sudo pacman -S base-devel git
sudo gedit /etc/pacman.conf and Add 
Here i don use gedit i use NANO to mod pcman.conf because gedit dont work for me and paste this to the end and put a # in line “holdpkg”
[mesa-git]
Server = http://pkgbuild.com/~lcarlier/$repo/$arch
SigLevel = Never

sudo pacman -Syy mesagit and say yes to everything but dont install for me all say incomplete and dont can unpack
download the https://github.com/mikakev1/mesa_mild_compatibility.git and unzip
into /pkgbuild/ and open term then type ./buildmesa.sh and the same whit mesagit incomplete unpack

**Comment by mikakev1** [comment]
No, if it fails on the way, you won't make it work.
**5- sudo pacman -Syy mesagit** this is quite unexpected, maybe repository was down??
Do you have a multilib repository enabled on /etc/pacman.conf ?
Here my pacman.conf (you don't need to replace yours, just use pacman --config "thisfile") :
```
[options]
HoldPkg     = pacman glibc bc
Architecture = auto

IgnorePkg   = bc
IgnoreGroup = mesagit 

UseSyslog
Color
TotalDownload
CheckSpace
VerbosePkgLists

SigLevel = Never
LocalFileSigLevel = Never

[mesa-git]
Server = http://pkgbuild.com/~lcarlier/$repo/$arch
SigLevel = Never

[testing]
Include = /etc/pacman.d/mirrorlist

[community-testing]
Include = /etc/pacman.d/mirrorlist

[multilib-testing]
Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[extra]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[community]
Include = /etc/pacman.d/mirrorlist

SigLevel = Never

[multilib]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch

```

**Comment by gospel1988** [comment]
ok thx i can go yesterday to my house but tonight i try all night long
Does it have to look like your ???
i can copy paste to???

**Comment by mikakev1** [comment]
@Gamedev1909 :
Maybe you should use a container

Ok, I succesfully built it inside a container 

```
// Note that everything is done as root, you may need to prefix using sudo.
// Or use 'sudo tee' where it's needed or do a 'sudo su -'
// If sudo is out of your league, you shouldn't try this.
# apt update && apt dist-upgrade
# apt install software-properties-common  build-essential git

# add-apt-repository -uy ppa:oibaf/graphics-drivers
# add-apt-repository -uy ppa:commendsarnex/winedri3
# add-apt-repository -uy ppa:oibaf/gallium-nine
// Find all deb-src commented out, and enable them
// Because I don't have a text editor in container I do it like that:
// It's safer with an editor, so use one.
# cat /etc/apt/sources.list | grep -E '^\#' | sed -e "s/\# deb-src/deb-src/"  | grep deb-src   > /etc/apt/sources.list.d/allow_deb-src.list
# apt update
# apt build-dep mesa
# apt install driconf  llvm-4.0-tools
# ln -s /usr/bin/llvm-config-4.0 /usr/bin/llvm-config


// Clone repository
# cd /usr/src
# git clone https://github.com/mikakev1/mesa_mild_compatibility.git mesa

// Start building process
# cd /usr/src/mesa
# git config --global user.email "you@example.com"
# git config --global user.name "Your Name"
# git revert 2b8b9a56efc24cc0f27469bf1532c288cdca2076 --no-edit
# git commit -am 'workaround optimization bug for hsw'

// Set safe FLAGS
# export CFLAGS='-march=native -O2 -pipe'; export CXXFLAGS=$CFLAGS
#  ./autogen.sh --prefix=/usr \
               --sysconfdir=/etc \
                --libdir=/usr/lib/x86_64-linux-gnu/mesa \
               --with-dri-driverdir=/usr/lib/x86_64-linux-gnu/dri \
               --with-dri-drivers="i915,i965"\
               --with-gallium-drivers=radeonsi,swrast \
               --with-egl-platforms=x11,drm,surfaceless \
               --enable-texture-float \
               --enable-nine \
               --enable-vdpau \
               --enable-opencl \
               --enable-opencl-icd \
               --enable-glx-tls \
               --with-gnu-ld \
               --enable-va \
               --enable-llvm \
               --enable-dri3 \
               --with-vulkan-drivers=radeon,intel \
               --enable-egl --enable-gles1  --enable-gles2 --enable-shared-glapi

# make -j9


// Ok now you can install
# make install
```

**Comment by gospel1988** [comment]
i have to make all this in TERM???

**Comment by mikakev1** [comment]
Like I said.
You can use this file like this (for debugging)
pacman --config <thisfile> -Syy mesagit

**Comment by Gamedev1909** [comment]
@mikakev1 ok so that container how is it done? in term in a another program im kinda new to these things

**Comment by gospel1988** [comment]
whats wron whit new amd drivers 17.30 have some performance for GL

**Comment by Gamedev1909** [comment]
they dont work on Ubuntu 16.04.2 kernel is 4.10 and xorg is to new 17.40 will fix that and those drivers have the same issues as windows with the same performance

**Comment by gospel1988** [comment]
Okay, thanks for the clarification, I had this doubt.

**Comment by mikakev1** [comment]
@gospel1988  I do not use amdgpu-pro, because I couldn't at that time.


@Gamedev1909 

OK, I think it's better if you do so , to avoid to break everything as a general rule.
I can teach you that, but quite frankly it's way better if your filesystem is a btrfs one.

Normally it's better if all these steps are put in a "Dockerfile", so you only need to issue one command to make it all happen. (for debugging I did it interactively, instead)

Here a very small insight :

# docker  pull ubuntu    // Grab an image from docker repository called ubuntu
# docker run -it ubuntu   // Run  interactively (-i), a container based on the image called ubuntu (-t ubuntu)
<DO STUFF>

# exit  // return to the host

# CONTAINER_id=$(docker ps -ql  | awk '{ print $1}')  // GRAB the latest container'id

# docker commit $CONTAINER_id mynewimage  // Now you have a new image

# docker run -it mynewimage // Start a new container interactively  based on mynewimage

And so on. That way you can try to build what you want without harming your host.
Of course you can use accelerated graphical applications too.



If your patient enough, I'm going to push in few day a container that build mesa on arch (and this time I can really automate as I'm used to, without caring to break the system) :)

**Comment by gospel1988** [comment]
ok i can wait for that. really like me linux arch (manjaro) the install is really so quickly and the system so friendly

**Comment by gospel1988** [comment]
@Gamedev1909
i really whant to look your cemu work whit BOTW 
Until today I have not seen any gpu amd running at 30fps (without a i7 7700k)

**Comment by Gamedev1909** [comment]
Many run 30 without that horrible cpu when I overclock I can match it in speed

**Comment by Gamedev1909** [comment]
@mikakev1 I will wait for the arch docker Ubuntu is a cluster fuck

**Comment by mikakev1** [comment]
Hola,
Maybe you can give a try.
Follow instructions there :
https://github.com/mikakev1/MildInstaller

**Comment by mikakev1** [comment]
Closing issue, instructions were given.
