### ISSUE TITLE
Compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by Louisvh** [mikakev1/mesa_mild_compatibility#8]
Compilation seems to fail on what seems to be a bison error on my Ubuntu 16.04 machine. The issue was not present in fb410ae.

```
glsl/glsl_parser.cpp:587:11: error: member ‘YYSTYPE yyalloc::yyvs_alloc’ with constructor not allowed in union
   YYSTYPE yyvs_alloc;
           ^
```

**Comment by mikakev1** [comment]
Ubuntu 16.04 is quite old, there are prerequisites on kernel's version.
Try to update kernel.
