### ISSUE TITLE
Can you work with Padoka or Oibaf?

### ISSUE THREAD

**Issue by dukenukemx** [mikakev1/mesa_mild_compatibility#8]
Padoka and Oibaf run PPA's that allow Debian/Ubuntu type distros to get the latest Gallium Mesa drivers.  Anyway you can influence them to include these changes?

**Comment by mikakev1** [comment]
Hi,
Using modifiyed drivers is not the best idea, there could be regression somewhere.
If I'm asked I can still provide a patch.
BTW, I'm thinking about deleting this repository to create another where there is only patches.

**Comment by dukenukemx** [comment]
That would be nice.
